### ISSUE TITLE
Suggestion: Make file names black

### ISSUE THREAD

**Issue by dertuxmalwieder** [Athari/CssGitHubWindows#5]
As Windows 95 (before C) didn't have "IE integration" for its Explorer just yet, this CSS could probably make file links have black text instead of blue text.

**Comment by dertuxmalwieder** [comment]
As Windows 95 mimicked (much of) NeXTStep, maybe a NeXTStep approach (underlined and/or italic text) would be enough?

**Comment by Athari** [comment]
Fixed in a542750b031386a5dacac588fae68393bd4a44d0.

@arhad File names, commit descriptions, links withing commit descriptions are all clickable in the file list. Making their style consistent would be in the spirit of classic Windows. I chose black color for all columns because otherwise there's too much blue. All links are underlined on hover.
